name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"
      - name: Enable cgo
        run: echo "CGO_ENABLED=1" >> $GITHUB_ENV
      - uses: cli/gh-extension-precompile@v1
        with:
          go_version: "1.23"
