name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@v2
        with:
          go_version: "1.21"
        env:
          CGO_ENABLED: 0
